In [10]:
df= pd.read_csv(r"C:\Users\ASUS\Downloads\customer_support_tickets_200k.csv")
df.head()

,ticket_id,customer_name,customer_email,product,category,issue_description,resolution_notes,priority,status,channel,...,ticket_resolved_date,escalated,sla_breached,operating_system,browser,payment_method,language,preferred_contact_time,issue_complexity_score,customer_segment
0,1,Patricia Smith,patricia.smith760@outlook.com,Web Portal,Account Suspension,The payment was deducted from my bank account ...,Data synchronization restored after backend se...,Urgent,Open,Email,...,2023-05-20,No,Yes,MacOS,Edge,PayPal,French,Afternoon,4,Small Business
1,2,Patricia Williams,patricia.williams390@gmail.com,Mobile App,Performance Issue,I found a bug in the latest update affecting r...,Provided step-by-step troubleshooting instruct...,Urgent,Closed,Email,...,2024-01-19,Yes,Yes,Windows,Firefox,PayPal,English,Afternoon,2,Small Business
2,3,William Anderson,william.anderson651@outlook.com,Web Portal,Performance Issue,The application crashes whenever I try to uplo...,Provided step-by-step troubleshooting instruct...,Medium,Closed,Chat,...,2022-12-05,Yes,Yes,Windows,Safari,Bank Transfer,French,Morning,4,Corporate
3,4,David Miller,david.miller672@icloud.com,Payment Gateway,Subscription Cancellation,My subscription was cancelled without my reque...,Provided step-by-step troubleshooting instruct...,Medium,Closed,Social Media,...,2024-04-04,Yes,No,Windows,Chrome,Credit Card,Spanish,Afternoon,7,Corporate
4,5,Robert Gonzalez,robert.gonzalez391@hotmail.com,Web Portal,Feature Request,The system is not syncing data across devices ...,We have reset the account credentials and advi...,High,Pending Customer,Email,...,2024-08-24,Yes,No,Linux,NaN,Debit Card,Spanish,Evening,3,Corporate

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 30 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   ticket_id                    200000 non-null  int64
 1   customer_name                200000 non-null  object
 2   customer_email               200000 non-null  object
 3   product                      200000 non-null  object
 4   category                     200000 non-null  object
 5   issue_description            200000 non-null  object
 6   resolution_notes             200000 non-null  object
 7   priority                     200000 non-null  object
 8   status                       200000 non-null  object
 9   channel                      200000 non-null  object
 10  region                       200000 non-null  object
 11  customer_age                 200000 non-null  int64
 12  customer_gender              200000 non-null  object
 13  subscription_type            200000 non-null  object
 14  customer_tenure_months       200000 non-null  int64
 15  previous_tickets             200000 non-null  int64
 16  customer_satisfaction_score  200000 non-null  int64
 17  first_response_time_hours    200000 non-null  float64
 18  resolution_time_hours        200000 non-null  float64
 19  ticket_created_date          200000 non-null  object
 20  ticket_resolved_date         200000 non-null  object
 21  escalated                    200000 non-null  object
 22  sla_breached                 200000 non-null  object
 23  operating_system             200000 non-null  object
 24  browser                      159977 non-null  object
 25  payment_method               200000 non-null  object
 26  language                     200000 non-null  object
 27  preferred_contact_time       200000 non-null  object
 28  issue_complexity_score       200000 non-null  int64
 29  customer_segment             200000 non-null  object
dtypes: float64(2), int64(6), object(22)
memory usage: 45.8+ MB

In [12]:
df['browser'] = df['browser'].fillna('Unknown')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 30 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   ticket_id                    200000 non-null  int64
 1   customer_name                200000 non-null  object
 2   customer_email               200000 non-null  object
 3   product                      200000 non-null  object
 4   category                     200000 non-null  object
 5   issue_description            200000 non-null  object
 6   resolution_notes             200000 non-null  object
 7   priority                     200000 non-null  object
 8   status                       200000 non-null  object
 9   channel                      200000 non-null  object
 10  region                       200000 non-null  object
 11  customer_age                 200000 non-null  int64
 12  customer_gender              200000 non-null  object
 13  subscription_type            200000 non-null  object
 14  customer_tenure_months       200000 non-null  int64
 15  previous_tickets             200000 non-null  int64
 16  customer_satisfaction_score  200000 non-null  int64
 17  first_response_time_hours    200000 non-null  float64
 18  resolution_time_hours        200000 non-null  float64
 19  ticket_created_date          200000 non-null  object
 20  ticket_resolved_date         200000 non-null  object
 21  escalated                    200000 non-null  object
 22  sla_breached                 200000 non-null  object
 23  operating_system             200000 non-null  object
 24  browser                      200000 non-null  object
 25  payment_method               200000 non-null  object
 26  language                     200000 non-null  object
 27  preferred_contact_time       200000 non-null  object
 28  issue_complexity_score       200000 non-null  int64
 29  customer_segment             200000 non-null  object
dtypes: float64(2), int64(6), object(22)
memory usage: 45.8+ MB

In [14]:
df['ticket_created_date'] = pd.to_datetime(df['ticket_created_date'], errors='coerce')
df['ticket_resolved_date'] = pd.to_datetime(df['ticket_resolved_date'], errors='coerce')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 30 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   ticket_id                    200000 non-null  int64
 1   customer_name                200000 non-null  object
 2   customer_email               200000 non-null  object
 3   product                      200000 non-null  object
 4   category                     200000 non-null  object
 5   issue_description            200000 non-null  object
 6   resolution_notes             200000 non-null  object
 7   priority                     200000 non-null  object
 8   status                       200000 non-null  object
 9   channel                      200000 non-null  object
 10  region                       200000 non-null  object
 11  customer_age                 200000 non-null  int64
 12  customer_gender              200000 non-null  object
 13  subscription_type            200000 non-null  object
 14  customer_tenure_months       200000 non-null  int64
 15  previous_tickets             200000 non-null  int64
 16  customer_satisfaction_score  200000 non-null  int64
 17  first_response_time_hours    200000 non-null  float64
 18  resolution_time_hours        200000 non-null  float64
 19  ticket_created_date          200000 non-null  datetime64[ns]
 20  ticket_resolved_date         200000 non-null  datetime64[ns]
 21  escalated                    200000 non-null  object
 22  sla_breached                 200000 non-null  object
 23  operating_system             200000 non-null  object
 24  browser                      200000 non-null  object
 25  payment_method               200000 non-null  object
 26  language                     200000 non-null  object
 27  preferred_contact_time       200000 non-null  object
 28  issue_complexity_score       200000 non-null  int64
 29  customer_segment             200000 non-null  object
dtypes: datetime64[ns](2), float64(2), int64(6), object(20)
memory usage: 45.8+ MB

In [16]:
df[['ticket_created_date','ticket_resolved_date']].head()

  ticket_created_date ticket_resolved_date
0          2023-05-17           2023-05-20
1          2024-01-06           2024-01-19
2          2022-11-30           2022-12-05
3          2024-03-21           2024-04-04
4          2024-08-16           2024-08-24

In [17]:
df['customer_id'] = df['customer_email']

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 31 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   ticket_id                    200000 non-null  int64
 1   customer_name                200000 non-null  object
 2   customer_email               200000 non-null  object
 3   product                      200000 non-null  object
 4   category                     200000 non-null  object
 5   issue_description            200000 non-null  object
 6   resolution_notes             200000 non-null  object
 7   priority                     200000 non-null  object
 8   status                       200000 non-null  object
 9   channel                      200000 non-null  object
 10  region                       200000 non-null  object
 11  customer_age                 200000 non-null  int64
 12  customer_gender              200000 non-null  object
 13  subscription_type            200000 non-null  object
 14  customer_tenure_months       200000 non-null  int64
 15  previous_tickets             200000 non-null  int64
 16  customer_satisfaction_score  200000 non-null  int64
 17  first_response_time_hours    200000 non-null  float64
 18  resolution_time_hours        200000 non-null  float64
 19  ticket_created_date          200000 non-null  datetime64[ns]
 20  ticket_resolved_date         200000 non-null  datetime64[ns]
 21  escalated                    200000 non-null  object
 22  sla_breached                 200000 non-null  object
 23  operating_system             200000 non-null  object
 24  browser                      200000 non-null  object
 25  payment_method               200000 non-null  object
 26  language                     200000 non-null  object
 27  preferred_contact_time       200000 non-null  object
 28  issue_complexity_score       200000 non-null  int64
 29  customer_segment             200000 non-null  object
 30  customer_id                  200000 non-null  object
dtypes: datetime64[ns](2), float64(2), int64(6), object(21)
memory usage: 47.3+ MB

In [19]:
df = df.sort_values(['customer_id','ticket_created_date'])

In [20]:
df['previous_ticket_date'] = df.groupby('customer_id')['ticket_created_date'].shift(1)

In [21]:
df['repeat_contact_flag'] = (
    (df['ticket_created_date'] - df['previous_ticket_date']).dt.days <= 5
).astype(int)

In [22]:
df[['customer_id','ticket_created_date','previous_ticket_date','repeat_contact_flag']].head(15)

,customer_id,ticket_created_date,previous_ticket_date,repeat_contact_flag
46365,barbara.anderson104@gmail.com,2023-09-06,NaT,0
177771,barbara.anderson105@gmail.com,2022-04-02,NaT,0
22079,barbara.anderson106@hotmail.com,2024-09-05,NaT,0
109464,barbara.anderson107@icloud.com,2024-04-19,NaT,0
55257,barbara.anderson108@outlook.com,2023-12-15,NaT,0
66854,barbara.anderson109@hotmail.com,2024-05-02,NaT,0
113338,barbara.anderson109@icloud.com,2024-11-08,NaT,0
196072,barbara.anderson10@icloud.com,2024-12-26,NaT,0
191808,barbara.anderson113@company.com,2022-06-20,NaT,0
194491,barbara.anderson116@gmail.com,2023-11-16,NaT,0
50916,barbara.anderson125@yahoo.com,2024-01-26,NaT,0
110766,barbara.anderson126@company.com,2022-10-23,NaT,0
50758,barbara.anderson126@yahoo.com,2022-03-25,NaT,0
55954,barbara.anderson12@icloud.com,2022-06-25,NaT,0
106579,barbara.anderson130@hotmail.com,2023-03-08,NaT,0

In [24]:
df['customer_id'].value_counts().head(10)

customer_id
barbara.martin919@yahoo.com       4
john.gonzalez711@gmail.com        4
william.moore661@company.com      4
susan.wilson217@gmail.com         4
richard.anderson171@icloud.com    4
mary.moore262@yahoo.com           4
elizabeth.thomas36@gmail.com      3
barbara.moore828@hotmail.com      3
karen.taylor975@outlook.com       3
thomas.smith20@yahoo.com          3
Name: count, dtype: int64

In [23]:
df[df['customer_id'] == 'barbara.anderson104@gmail.com']

,ticket_id,customer_name,customer_email,product,category,issue_description,resolution_notes,priority,status,channel,...,operating_system,browser,payment_method,language,preferred_contact_time,issue_complexity_score,customer_segment,customer_id,previous_ticket_date,repeat_contact_flag
46365,46366,Barbara Anderson,barbara.anderson104@gmail.com,E-commerce Store,Payment Problem,The application crashes whenever I try to uplo...,We have reset the account credentials and advi...,Medium,Resolved,Web Form,...,MacOS,Unknown,PayPal,English,Night,1,Corporate,barbara.anderson104@gmail.com,NaT,0

In [25]:
df[df['customer_id'] == 'barbara.martin919@yahoo.com']

,ticket_id,customer_name,customer_email,product,category,issue_description,resolution_notes,priority,status,channel,...,operating_system,browser,payment_method,language,preferred_contact_time,issue_complexity_score,customer_segment,customer_id,previous_ticket_date,repeat_contact_flag
142293,142294,Barbara Martin,barbara.martin919@yahoo.com,Cloud Storage,Bug Report,I am experiencing very slow performance while ...,Security settings updated and customer notifie...,High,Resolved,Web Form,...,Android,Edge,Debit Card,French,Night,5,Individual,barbara.martin919@yahoo.com,NaT,0
30452,30453,Barbara Martin,barbara.martin919@yahoo.com,E-commerce Store,Data Sync Issue,I am experiencing very slow performance while ...,Explained billing breakdown and clarified appl...,High,Pending Customer,Phone,...,Linux,Firefox,Crypto,Chinese,Afternoon,8,Corporate,barbara.martin919@yahoo.com,2022-10-09,0
157278,157279,Barbara Martin,barbara.martin919@yahoo.com,CRM Platform,Bug Report,There seems to be a discrepancy in my billing ...,Bug logged internally and workaround shared wi...,Urgent,Open,Email,...,Linux,Chrome,Credit Card,Chinese,Afternoon,2,Corporate,barbara.martin919@yahoo.com,2022-11-28,0
43584,43585,Barbara Martin,barbara.martin919@yahoo.com,Billing System,Performance Issue,I am unable to access my account after enterin...,Explained billing breakdown and clarified appl...,Urgent,Resolved,Chat,...,Linux,Firefox,Crypto,Spanish,Evening,2,Individual,barbara.martin919@yahoo.com,2023-08-29,0

In [26]:
df['repeat_contact_flag'].value_counts()

repeat_contact_flag
0    199925
1        75
Name: count, dtype: int64

In [27]:
df['repeat_contact_flag'] = (
    (df['ticket_created_date'] - df['previous_ticket_date']).dt.days <= 10
).astype(int)

In [28]:
df['repeat_contact_flag'].value_counts()

repeat_contact_flag
0    199850
1       150
Name: count, dtype: int64

In [29]:
df['repeat_contact_flag'] = (
    ((df['ticket_created_date'] - df['previous_ticket_date']).dt.days <= 15) |
    (df['previous_tickets'] > 0)
).astype(int)

In [30]:
df['repeat_contact_flag'].value_counts()

repeat_contact_flag
1    190482
0      9518
Name: count, dtype: int64

In [31]:
df['repeat_contact_flag'] = (
    (df['ticket_created_date'] - df['previous_ticket_date']).dt.days <= 30
).astype(int)

In [32]:
df['repeat_contact_flag'].value_counts()

repeat_contact_flag
0    199561
1       439
Name: count, dtype: int64

In [33]:
df.sample(5000).to_csv("sample_data.csv", index=False)